apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    orgId: 1
    url: http://influxdb:8086
    database: nr_kpi
    user: admin
    password: admin
    basicAuth: false
    isDefault: true
    jsonData:
      timeInterval: "1s"
    version: 1
    editable: false
